;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	LaTeX-babel-insert-hyphen
	TeX-insert-backslash
	beginning-of-visual-line
	diredp-previous-line
	end-of-visual-line
	insert-numbers-from-one
	keyboard-escape-quit
	kill-visual-line
	move-line-down
	move-line-up
	org-self-insert-command
	sgml-slash
	))

(setq mc/cmds-to-run-once
      '(
	backward-sentence
	beginning-of-buffer
	end-of-buffer
	helm-M-x
	indent-for-tab-command
	kill-region
	mouse-set-secondary
	mouse-start-secondary
	scroll-bar-toolkit-scroll
	wdired-finish-edit
	))
