;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	LaTeX-babel-insert-hyphen
	LaTeX-insert-left-brace
	TeX-insert-backslash
	beginning-of-visual-line
	diredp-previous-line
	end-of-visual-line
	ess-smart-comma
	insert-numbers-from-one
	keyboard-escape-quit
	kill-region
	kill-visual-line
	markdown-outdent-or-delete
	move-line-down
	move-line-up
	org-self-insert-command
	sgml-slash
	))

(setq mc/cmds-to-run-once
      '(
	beginning-of-buffer
	comment-dwim
	dired-toggle-read-only
	end-of-buffer
	helm-M-x
	indent-for-tab-command
	markdown-forward-paragraph
	mouse-set-region
	mouse-set-secondary
	mouse-start-secondary
	org-cycle
	phi-replace-query
	scroll-bar-toolkit-scroll
	wdired-finish-edit
	))
